dist: xenial
sudo: false
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libsdl2-dev
      - gcc-6
      - g++-6
      - cmake
script:
  - gcc -v && g++ -v && cmake --version
  - cmake .
  - make && make test
