dist: xenial
sudo: false
language:
  - cpp
compiler:
  - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang
      - cmake
      - libasound2-dev
script:
  - mkdir build
  - pushd build
  - cmake ..
  - make && make test
  - popd
