dist: xenial
sudo: false
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - cmake
      - libasound2-dev
      - texinfo
      - autotools-dev
script:
  - export IS_CM_BUILD=1
  - export CC=gcc-8
  - export CXX=g++-8
  - . scripts/env.sh
  - jones_test_asan
