dist: xenial
sudo: false
language:
  - cpp
compiler:
  - gcc
env:
  - IS_CM_BUILD=1
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - cmake
      - libasound2-dev
      - texinfo
      - autotools-dev
script:
  - export CC=gcc-8
  - export CXX=g++-8
  - gcc -v && g++ -v && cmake --version
  - cmake .
  - make && make test
