trigger:
- master

resources:
 containers:
   - container: build_container
     image: thejunkjon/jones

container: build_container

steps:
- checkout: self
  submodules: true

- script: |
    . scripts/env.sh
  displayName: 'Setup Environment'

- script: |
    jones_build
  displayName: 'Build'

- script: |
    jones_test_cm
  displayName: 'Test'
