trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

container: ubuntu:18.04

steps:
- checkout: self
  submodules: true

- script: 'sudo apt update && sudo apt install -y git build-essential cmake libasound2-dev texinfo gcc-8 g++-8 autotools-dev automake autoconf libtool'
  displayName: 'Setup Environment'

- script: '. scripts/env.sh && jones_cm'
  displayName: 'Build'
