trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  submodules: true

- script: 'sudo apt update && sudo apt install -y build-essential cmake libasound2-dev texinfo gcc-8 g++-8'
  displayName: 'Setup Environment'

- script: '. scripts/env.sh && jones_cm'
  displayName: 'Build'
