trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: 'sudo apt update && sudo apt install -y build-essential cmake libasound2-dev texinfo gcc'
  displayName: 'Setup Environment'
- script: '. scripts/env.sh && jones_cm'
  displayName: 'Build'
