trigger:
- master

resources:
 containers:
   - container: build_container
     image: thejunkjon/jones

container: build_container

steps:
- checkout: self
  submodules: true

- script: |
    . scripts/env.sh
    jones_cm
  displayName: 'Build'
