version: '3'
services:

  jones: &jones
    depends_on:
      - 'emsdk'
    build:
      dockerfile: 'cm/docker/base/Dockerfile'
      context: .
    volumes:
      - '.:/jones'
    working_dir: '/jones'

  jones-flutter:
    <<: *jones
    depends_on:
      - 'jones'
    build:
      dockerfile: 'cm/docker/flutter/Dockerfile'
      context: .

  jones-dev:
    <<: *jones
    depends_on:
      - 'jones-flutter'
    build:
      dockerfile: 'cm/docker/dev/Dockerfile'
      context: .
    volumes:
      - '.:/jones'
      - '/tmp/.X11-unix:/tmp/.X11-unix'
      - '$HOME/.Xauthority:/home/jones/.Xauthority'
    environment:
      - DISPLAY
    tty: true
    user: $JONES_UID

  emsdk:
    build:
      dockerfile: 'docker/Dockerfile'
      context: 'external/wasm/emsdk/source'
      args:
        - EMSCRIPTEN_VERSION=2.0.12
