version: '3'
services:
  jones:
    depends_on:
      - 'emsdk'
    build:
      dockerfile: 'cm/Dockerfile'
      context: .
    volumes:
      - '.:/jones'
    working_dir: '/jones'
    tty: true
    user: $JONES_UID
  emsdk:
    build:
      dockerfile: 'docker/Dockerfile'
      context: 'external/wasm/emsdk/source'
      args:
        - EMSCRIPTEN_VERSION=2.0.12
