version: '3'
services:

  jones:
    depends_on:
      - 'emsdk'
    build:
      dockerfile: 'cm/docker/base/Dockerfile'
      context: .
    volumes:
      - '.:/jones'
    working_dir: '/jones'
    tty: true
    user: $JONES_UID

  jones-flutter: &jones-flutter
    depends_on:
      - 'jones'
    build:
      dockerfile: 'cm/docker/flutter/Dockerfile'
      context: .
    volumes:
      - '.:/jones'
    working_dir: '/jones'
    tty: true
    user: $JONES_UID

  jones-flutter-gui:
    <<: *jones-flutter
    volumes:
      - '.:/jones'
      - '/tmp/.X11-unix:/tmp/.X11-unix'
      - '$HOME/.Xauthority:/home/jones/.Xauthority'
    environment:
      - DISPLAY

  emsdk:
    build:
      dockerfile: 'docker/Dockerfile'
      context: 'external/wasm/emsdk/source'
      args:
        - EMSCRIPTEN_VERSION=2.0.12
