name: Build Master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build Jones Project
      run:  ./scripts/env.sh jones_build_cm

    - name: Run Unit Tests
      run:  ./scripts/env.sh jones_test_cm

    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: archive-artifacts
        path: out/jones/**/*.*
