name: Build Master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Free Disk Space
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        docker rmi $(docker image ls -aq)
        df -h

    - name: Checkout Source
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Check Environment
      run:  ./dev/scripts/env.sh jones_check_environment

    - name: Build Jones Project
      run:  ./dev/scripts/env.sh jones_build_cm

    - name: Run Unit Tests
      run:  ./dev/scripts/env.sh jones_test_cm

    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: archive-artifacts
        path: |
          out/default/jones/**/*.*
          out/flutter/**/*.*
